theme = "gruvbox_dark_soft_custom"

[editor]
# Make the editor respond to keystrokes faster ie faster autocomplete
idle-timeout = 0
# Not sure why this is here... I never use it
auto-save = true
# always add gutter space for git diff etc. IE the green lines on the left. 
# This makes it so the editor doesn't shift left and right
bufferline = "always"
# How many lines to scroll on a single mouse scroll (makes lines go twice as fast)
scroll-lines = 2
# RElattive lines show how far away any given line is. Useful for jumping between lines using 5J or 15K
line-number = "relative"
# Always keep at least 4 lines above and below the cursor in view
scrolloff = 4
# Use a thin line as the cursor when in insert mode
cursor-shape.insert = "bar"
# Wrap lines when they grow past the width of the view
soft-wrap.enable = true
# soft-wrap.wrap-indicator = "↪ "
gutters = ["diagnostics", "spacer", "line-numbers", "spacer"]
completion-timeout = 10
cursorline = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.file-picker]
# Show hidden files in the file picker
hidden = false

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["diagnostics"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[keys.normal]
# Use Control K as my version of escape
C-k = ["collapse_selection", "keep_primary_selection"]
C-e = "increment"
# 55
# in unix systems suspending takes you back to the terminal while leaving the editor open. Then you
# can jump back into the editor by typing the command 'fg' in the terminal
# C-f = "suspend"
# Get documenation popups with capital k
K = "hover"

# "write" shortcut
[keys.normal.space]
# Use space - w to save the file
w = ":write"
# space - q to readjust lines to a max width of 100 chars
q = ":reflow 100"

# Display options
[keys.normal.space.d]
# space - d - h to toggle inlay hints on and off
h = ":toggle lsp.display-inlay-hints"
d = ":toggle lsp.display-inline-diagnostics"


# "buffer close" shortcuts
[keys.normal.space.b.c]
c = ":buffer-close"
f = ":buffer-close!"
o = ":buffer-close-others"

# "editor" shortcuts
[keys.normal.space.e]
r = ":config-reload"

# "escape"
[keys.insert]
C-k = "normal_mode"
# C-f = "suspend"
[keys.select]
C-k = "normal_mode"
# C-f = "suspend"
