[[language]]
name = "markdown"
file-types = ["md"]
auto-format = true
formatter = {command = "npx", args = ["prettier", "--write", "--parser=markdown", "--prose-wrap=always", "--print-width=100"]}

[[language]]
name="java"
auto-format = true
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
# language-servers = [{ command = "jdtls" }]
indent = { tab-width = 4, unit = "    " }
# [language.config.java.inlayHints]
# parameterNames.enabled = "all"


[[language]]
name = "monkey"
file-types = ["dmd"]
scope = "source.dmd"
comment-token = "//"
roots = []
indent = {tab-width = 4, unit = "    "}

[[grammar]]
name = "monkey"
source = {path = "/Users/jaredmoulton/Developer/tree-sitter-monkey", rev="29ba8a602388119dca0a2553f9f1246ceece291e"}


[[language]]
name = "slint"
file-types = ["slint"]
scope = "source.slint"
comment-token = "//"
roots = []
indent = {tab-width = 4, unit = "    "}

[[grammar]]
name = "slint"
source = {path = "/Users/jaredmoulton/Developer/slint/master/editors/tree-sitter-slint", rev="56e42734d78e585c1fa11531d97ac502c790fe06"}

# [[language]]
# name = "typst"
# scope = "source.typst"
# injection-regex = "^typ(st)?$"
# file-types = ["typ"]
# comment-token = "//"
# indent = { tab-width = 2, unit = "  " }
# roots = ["typst.toml"]
# [language.auto-pairs]
# '(' = ')'
# '{' = '}'
# '[' = ']'
# '"' = '"'
# '`' = '`'
# '$' = '$'

# [[grammar]]
# name = "typst"
# source = { path = "/Users/jaredmoulton/Developer/tree-sitter-typst" }



[language-server.typst-lsp]
command = "typst-lsp"

[[language]]
name = "c"
auto-format = true

[[language]]
name = "nasm"
# language-server = [ "asm-lsp" ]
