#:schema ~/Developer/lapce/extra/schemas/color-theme.json

[color-theme]
name = "Gruvbox Light Soft"

[ui]
font-family = ""
scroll-width = 10
drop-shadow-width = 10

[color-theme.base]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
grey = "#928374"
magenta = "#b16286"
orange = "#d65d0e"
purple = "#d3869b"
red = "#cc241d"
white = "#fbf1c7"
yellow = "#d79921"
hovered-background = "#ebdbb2"
dark-grey = "#3c3836"
light-grey = "#d5c4a1"
light-grey-alpha = "#a89984BB"
medium-grey = "#ebdbb2"
light-blue = "#83a598"
light-green = "#8ec07c55"
light-brown = "#665c5455"
transparent-black = "#00000000"
dark-grey-alpha = "#92837420"
yellow-alpha = "#d7992120"
red-alpha = "#cc241d20"

[color-theme.syntax]
"comment" = "#7c6f64"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$yellow"
"struct" = "$yellow"
"structure" = "$yellow"
"interface" = "$yellow"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$green"
"method" = "$green"
"function.method" = "$blue"
"keyword" = "$red"
"selfKeyword" = "$cyan"
"field" = "$cyan"
"property" = "$black"
"enumMember" = "$yellow"
"enum-member" = "$yellow"
"string" = "$green"
"type.builtin" = "$yellow"
"builtinType" = "$yellow"
"escape" = "$cyan"
"string.escape" = "$cyan"
"embedded" = "$cyan"
"punctuation.delimiter" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
"text.reference" = "$yellow"
"variable" = "$black"
"variable.other.member" = "$black"
"tag" = "$blue"

[color-theme.ui]
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "$black"
"lapce.border" = "$medium-grey"
"lapce.scroll_bar" = "$light-grey-alpha"

"lapce.button.primary.background" = "$green"
"lapce.button.primary.foreground" = "$black"

# tab
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "$blue"

"lapce.tab.inactive.background" = "$light-grey"
"lapce.tab.inactive.foreground" = "$black"
"lapce.tab.inactive.underline" = "$light-blue"

"lapce.tab.separator" = "$transparent-black"

"lapce.icon.active" = "$black"
"lapce.icon.inactive" = "$grey"

"lapce.remote.icon" = "$black"
"lapce.remote.local" = "$blue"
"lapce.remote.connected" = "$green"
"lapce.remote.connecting" = "$yellow"
"lapce.remote.disconnected" = "$red"

"lapce.plugin.name" = "$dark-grey"
"lapce.plugin.description" = "$black"
"lapce.plugin.author" = "$medium-grey"

"editor.background" = "$white"
"editor.foreground" = "$black"
"editor.dim" = "$grey"
"editor.focus" = "$dark-grey"
"editor.caret" = "$blue"
"editor.selection" = "$light-grey-alpha"
"editor.current_line" = "$light-grey"
"editor.link" = "$blue"
"editor.visible_whitespace" = "$grey"
"editor.indent_guide" = "$grey"
"editor.drag_drop_background" = "$light-green"
"editor.drag_drop_tab_background" = "$light-brown"
"editor.sticky_header_background" = "$white"

"inlay_hint.foreground" = "$black"
"inlay_hint.background" = "$light-blue"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "$red-alpha"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "$yellow-alpha"
"error_lens.other.foreground" = "$grey"
"error_lens.other.background" = "$dark-grey-alpha"

"source_control.added" = "$green"
"source_control.removed" = "$red"
"source_control.modified" = "$blue"

"palette.background" = "$light-grey"
"palette.foreground" = "$black"
"palette.current.background" = "$medium-grey"
"palette.current.foreground" = "$black"

"completion.background" = "$light-grey"
"completion.current" = "$medium-grey"

"hover.background" = "$hovered-background"

"activity.background" = "$light-grey"
"activity.current" = "$black"

"debug.breakpoint" = "$red"
"debug.breakpoint.hover" = "$grey"

"panel.background" = "$light-grey"
"panel.foreground" = "$black"
"panel.foreground.dim" = "$grey"
"panel.current.background" = "$medium-grey"
"panel.current.foreground" = "$black"
"panel.current.foreground.dim" = "$grey"
"panel.hovered.background" = "$hovered-background"
"panel.hovered.active.background" = "$grey"
"panel.hovered.foreground" = "$black"
"panel.hovered.foreground.dim" = "$grey"

"status.background" = "$light-grey"
"status.foreground" = "$black"
"status.modal.normal.background" = "$blue"
"status.modal.normal.foreground" = "$black"
"status.modal.insert.background" = "$red"
"status.modal.insert.foreground" = "$black"
"status.modal.visual.background" = "$yellow"
"status.modal.visual.foreground" = "$black"
"status.modal.terminal.background" = "$purple"
"status.modal.terminal.foreground" = "$black"

"markdown.blockquote" = "$dark-grey"

"terminal.cursor" = "$black"
"terminal.foreground" = "$black"
"terminal.background" = "$white"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "$dark-grey"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "$grey"
